server:
  port: 10010
spring:
  application:
    name: gateway
  security:
    user:
      name: root
      password: 217024
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 217024
    url: jdbc:mysql://192.168.17.14:3306/server?useUnicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 30
      maximum-pool-size: 50
      minimum-idle: 5
  redis:
    host: 192.168.17.14
    port: 6379
    database: 0
    password: 217024
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 2
jwt:
  expire: 1800
  secrt: ruan
  head: token
jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  hiddenPackages: ruan.provider
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
      limit: 100
  remote:
    default:
      type: redis.lettuce4
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      uri:
        - redis://217024@192.168.17.14:6379/1