server:
  port: 10010
spring:
  application:
    name: gateway
  security:
    user:
      name: root
      password: 217024
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 217024
    url: jdbc:mysql://192.168.17.14:3306/server?useUnicode=true&characterEncoding=UTF-8
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      idle-timeout: 30
      maximum-pool-size: 50
      minimum-idle: 5
jwt:
  expire: 30
  secrt: ruan
  head: token