server:
  port: 8080
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.24.14:9876
      bindings:
        output:
          content-type: application/json
          group: rocketmq-product
          destination: test-rocketmq
          binder: rocketmq
        input:
          content-type: application/json
          group: rocketmq-consumer
          destination: test-rocketmq
          binder: rocketmq
        kafkaoutput:
          content-type: application/json
          group: kafka-product
          destination: test-kafka
          binder: kafka
        kafkainput:
          content-type: application/json
          group: kafka-consumer
          destination: test-kafka
          binder: kafka
      kafka:
        binder:
          brokers: 192.168.24.14:9092
    nacos:
      discovery:
        heart-beat-interval: 30
        heart-beat-timeout: 90
        server-addr: 192.168.24.14:8848
        enabled: true
        group: nacos-group
        namespace: 2ca20bb8-f886-461b-8458-549dfba803c0
        service: nacos-provider
  datasource:
    url: jdbc:mysql://192.168.24.14:3306/server?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 217024
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 2
    maxActive: 300
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    default-property-inclusion: non_null
    date-format: java.text.SimpleDateFormat
  redis:
    host: 192.168.24.14
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1000ms
        min-idle: 0
    port: 6379
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
elaticjob:
  zookeeper:
    server-lists: 192.168.24.14:2181,192.168.24.14:2182,192.168.24.14:2183
    namespace: elasticjob
logging:
  config: classpath:logback-spring.xml